server:
  port: 8080
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/Pizzeria
    username: postgres
    password: 1
  liquibase:
    change-log: classpath:db/migration/db.changelog-master.yaml
    enabled: true
