version: '3.8'

volumes:
  pg_pizzeria:

networks:
  pizzeria_network:

services:
  pizzeria_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1
      - POSTGRES_DB=pizzeria
    volumes:
      - pg_pizzeria:/var/lib/postgresql/data
    networks:
      - pizzeria_network
    ports:
      - "5432:5432"

  app:
    restart: always
    build: .
    ports:
      - "8095:8095"
    depends_on:
      - pizzeria_db
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://pizzeria_db:5432/pizzeria'
      JAVA_OPTS: '-Xmx512m'
    networks:
      - pizzeria_network

  frontend:
    build:
      context: .
      dockerfile: ./front/Dockerfile
    restart: always
    ports:
      - "80:3000"
    depends_on:
      - pizzeria_db
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://pizzeria_db:5432/pizzeria'
    networks:
      - pizzeria_network

